GitlabRunnerのAutoscaling機能の導入手順を追加
Fintan-contents/collaborage pull request #20
Opened 2023-09-07 08:55 UTC by oguchi-shiori03

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +ここでは、[GitLab Runnerの機能であるAutoscaling](https://docs.gitlab.com/runner/configuration/runner_autoscale_aws/)の利用設定を行います。
【レビュー指摘転記】
ここを見出しにしてしまうと、後続の作業内容説明がこの見出しの項目内にあるように見えます。参考URLは一番最初の文にリンク埋め込んでしまったほうがいいかと思いました。

ここでは、[GitLab Runnerの機能であるAutoscaling](https://docs.gitlab.com/runner/configuration/runner_autoscale_aws/)の利用設定を行います。

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +    - Autoscalingで起動されたインスタンスからCIサーバへの接続が可能となるように設定します。
【レビュー指摘転記】
接続元、接続先の関係が初見で混乱しました。↓の方が読みやすいかなと思います。

- CIサーバのnexusからdockerイメージ取得する際に利用します。
- Autoscalingで起動されたインスタンスからCIサーバへの接続が可能となるように設定します。

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +    - CIサーバからAutoscalingで起動されたインスタンスへの接続が可能となるように設定します。
【レビュー指摘転記】
19081はCIサーバで開放するポート、2376と22は起動されたインスタンスで開放するポートという理解で合ってますか？
CIサーバで開放するポートとAutoscalingで起動されたインスタンスで開放するポートという形にグループ化した方がわかりやすいかと思いました。

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +- プロキシ環境下の場合は、Autoscaling用のAMIの設定を変更します。
【レビュー指摘転記】
Autoscalingの際はAMIを指定できること、プロキシ環境にない場合はどういうAMIを指定する（何も指定しない？）のかということも記載した方がいいと思いました。

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +- 以下はubuntu20.04を利用する場合のAMI設定例です。
【レビュー指摘転記】
このベースのAMIって提供必要なものでしょうか？ubuntuにDockerインストールしてproxy設定したものですか？必要なのは任意のAMIからインスタンス立ててDockerインストールして自分の環境に合わせてproxy設定することですかね？利用者に任意のAMIから作ってもらえば管理するAMIが減るかと思ったんですが、これを提供することによる利用者のメリットが正確にわからなかったので質問です。

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +  ここでの作業内容は次の通りです。
【レビュー指摘転記】
最初に箇条書きでどういうステップで何を作るのかを書いてもらった方がわかりやすいかと思いました。

- ubuntuのAMI使ってインスタンス立てる
- パッケージ管理にプロキシ設定する
- 環境変数にプロキシ設定する
- Dockerインストールする
- Dockerにプロキシ設定する
- 出来上がったインスタンスをもとにプロキシ設定されたAMIを作成する

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +# プロキシ環境下の場合
【レビュー指摘転記】
プロキシ環境下の場合に必要な手順とプロキシがない環境でも必要な手順とがわかるように（プロキシない場合に読み飛ばせるように）しておいて欲しいです、今の書き方だと上から順に読んで「これはプロキシだから要らないな」と判断していかないといけないのが少し面倒に感じました。

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +            NO_PROXY: 192.0.0.0/16
【レビュー指摘転記】
CIサーバのIPも同一サブネットのIP範囲に含まれてるので冗長に見えますが、これは利用者の環境によっては同一サブネットじゃないことがあり得るということでしょうか？

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +# Collaborage1.1環境をご利用の場合
【レビュー指摘転記】
これは既存Collaborage環境の利用者向けの記載ですか？
毛色が違うので、別途項目を設けたほうがいいかと思いました。
「Collaborage1.1環境をご利用の場合」みたいな案内を別出しして、AutoscalingはGitLabのXXバージョンから利用できるのでそれ以上にバージョンアップしてくださいというような案内かなと。

2023-09-07 09:04 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +        "amazonec2-region=<collaborage環境のregion>",
【レビュー指摘転記】
この辺は利用者の環境次第かなと思いました。

2023-09-07 09:06 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +ここでは、[GitLab Runnerの機能であるAutoscaling](https://docs.gitlab.com/runner/configuration/runner_autoscale_aws/)の利用設定を行います。
冒頭の説明文の中に参考URLのリンク埋め込みを行いました。

2023-09-07 09:06 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +    - Autoscalingで起動されたインスタンスからCIサーバへの接続が可能となるように設定します。
記載いただいた内容に文言を修正しました。
CIサーバ→Autoscaling用のインスタンスへの接続に関しても同様の修正を行っています。

2023-09-07 09:09 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +    - CIサーバからAutoscalingで起動されたインスタンスへの接続が可能となるように設定します。
以下の構成に記載を修正しました。

- CIサーバの開放ポート
  - 19081
- Autoscalingで起動されたインスタンスの開放ポート
  - 2376
  - 22

2023-09-07 09:14 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +- プロキシ環境下の場合は、Autoscaling用のAMIの設定を変更します。
config.tomlの設定内に設定AMIについての記載を追加しました。
https://github.com/Fintan-contents/collaborage/blob/feature-gitlab-autoscaling/doc/autoscaling.md#configtoml%E3%82%92%E4%BF%AE%E6%AD%A3%E3%81%97%E3%81%BE%E3%81%99

2023-09-07 09:14 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +- 以下はubuntu20.04を利用する場合のAMI設定例です。
なるべく作業者の手間を減らしたほうがいいかと思い提供を想定していましたが、必須ではない＋作成手順の例を記載しているため、作業者が任意にAMIを作成するよう修正しました。

2023-09-07 09:15 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +  ここでの作業内容は次の通りです。
インスタンス作成の項の先頭に、作業の概要を箇条書きで記載しました

2023-09-07 09:16 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +# プロキシ環境下の場合
作業手順を
1. Collaborage1.1環境で必要な作業
2. プロキシ環境で必要な作業
3. 共通で必要な作業

に分類し、手順の順番を変更、1、2の作業に関して見出しを追加しました。

2023-09-07 09:16 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +            NO_PROXY: 192.0.0.0/16
同一サブネットになる想定なので、CIサーバーの記載を削除しました。

2023-09-07 09:16 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +# Collaborage1.1環境をご利用の場合
「Collaborage1.1環境をご利用の場合」の項目を別途作成しました。

2023-09-07 09:17 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +        "amazonec2-region=<collaborage環境のregion>",
利用者の環境に合わせて設定が必要になるという内容に変更しました

2023-09-07 10:00 UTC, kumagoro1202 requested changes

2023-09-07 10:00 UTC, kumagoro1202 commented on doc/autoscaling.md
> +Autoscalingのプロパティ`--amazonec2-security-group-readonly`はgitlab-runner:ubuntu-v12.5.0、環境変数NO_PROXYのブロック指定ははgitlab-runner:ubuntu-v12.6.0から利用可能となるため、12.6以降のバージョンに更新します。
GitLabのバージョンはDockerイメージのタグではなく、GitLabのバージョンで記載してください。GitLab 12.5.0とか。

2023-09-07 10:00 UTC, kumagoro1202 commented on doc/autoscaling.md
> +  - AMIの保存方法は[アプリの復元](aws.md#アプリの復元)を参照して作業します。
アプリの復元はAMIを使ってインスタンス作成する手順ではないでしょうか。AMIの保存方法は[リカバリに備えてAMIを作成します](https://github.com/Fintan-contents/collaborage/blob/feature-gitlab-autoscaling/doc/ami.md#%E3%83%AA%E3%82%AB%E3%83%90%E3%83%AA%E3%81%AB%E5%82%99%E3%81%88%E3%81%A6ami%E3%82%92%E4%BD%9C%E6%88%90%E3%81%97%E3%81%BE%E3%81%99)ではないですか。
また内容的に薄いのでリンクせずにここに書いてしまっていいと思いました。

2023-09-07 10:00 UTC, kumagoro1202 commented on doc/autoscaling.md
> +          NO_PROXY: <同一サブネットのIP範囲>
NO_PROXYだけenv_fileに記載せずにenvironmentで指定しているのはなぜですか？

2023-09-07 10:00 UTC, kumagoro1202 commented on doc/autoscaling.md
> +        "amazonec2-zone=<collaborage環境のregion>",
regionじゃなくAZ？

2023-09-07 10:00 UTC, kumagoro1202 commented on doc/autoscaling.md
> +        "amazonec2-iam-instance-profile=<collaborage環境のロール名>",
「Collaborage環境の」より「自身の環境の」とかの方がいいと思いました。

2023-09-07 10:00 UTC, kumagoro1202 commented on doc/autoscaling.md
> +            - 未設定の場合はGitLab RunnerのデフォルトのAMIが設定されますが、2023年9月時点では起動時にエラーが発生するため特定のAMIを設定してください。
起動時に出るエラーってどんなエラーですか？

2023-09-07 10:00 UTC, kumagoro1202 commented on doc/autoscaling.md
> +        "amazonec2-security-group=<collaborage環境のセキュリティグループ名>",
ここで指定するセキュリティグループってどういう設定のセキュリティグループか説明した方がいいんじゃないでしょうか。

2023-09-07 10:00 UTC, kumagoro1202 commented on doc/autoscaling.md
> +        - ROLE_NAME
こういう風に書けばいいのではと言ったものの実際に見ると違和感がありました。（ここに書いてるキーとかだけじゃなくregionとかも環境にあわせて読み替えるものじゃないかと）この注意書きなしでいいかなと思いました。

2023-09-08 04:36 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +  - AMIの保存方法は[アプリの復元](aws.md#アプリの復元)を参照して作業します。
作成方法を直接記載する形式に修正しました。

2023-09-08 04:36 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +Autoscalingのプロパティ`--amazonec2-security-group-readonly`はgitlab-runner:ubuntu-v12.5.0、環境変数NO_PROXYのブロック指定ははgitlab-runner:ubuntu-v12.6.0から利用可能となるため、12.6以降のバージョンに更新します。
記載を修正しました。

2023-09-08 04:36 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +          NO_PROXY: <同一サブネットのIP範囲>
他のアプリはNO_PROXYの設定が不要なため分けて記載していました。
ですが、NO_PROXYの設定があっても問題ないためcommon.envにまとめるように修正しました。

2023-09-08 04:36 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +        "amazonec2-zone=<collaborage環境のregion>",
記載が誤っていたため修正しました。

2023-09-08 04:36 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +        "amazonec2-iam-instance-profile=<collaborage環境のロール名>",
記載を修正しました。

2023-09-08 04:37 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +            - 未設定の場合はGitLab RunnerのデフォルトのAMIが設定されますが、2023年9月時点では起動時にエラーが発生するため特定のAMIを設定してください。
AWS環境で再度動作確認を行いましたが、エラーは未発生でした（検証開始時だったため、ポート等の設定が不足していた可能性があります）。
そのため、AMIが未設定の場合に利用されるデフォルトAMIについての記載を追加し、未設定時にエラーが発生するという内容を削除しました。

2023-09-08 04:37 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +        "amazonec2-security-group=<collaborage環境のセキュリティグループ名>",
追加したポートの設定が適用されるセキュリティグループを設定する必要がある旨を追記しました。

2023-09-08 04:37 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +        - ROLE_NAME
注意書きを削除しました。

2023-09-08 05:32 UTC, kumagoro1202 requested changes

2023-09-08 05:32 UTC, kumagoro1202 commented on doc/autoscaling.md
> +        ```
上とまったく同じだから不要ではないですか？
あとGitLab Runnerのバージョン古くないですか？

2023-09-08 05:32 UTC, kumagoro1202 commented on doc/autoscaling.md
> +# サーバのポートを開放します
この手順って具体的にはセキュリティグループの設定でしたっけ？ここだけ何をしたら開放済みになるかがわからないなと思いました。ここでいう開放がinboundにポート設定済みのセキュリティグループを作ることならここで作ったセキュリティグループを後続のconfig.tomlで設定すると繋がるなと思いました。

2023-09-08 06:19 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +        ```
設定例は不要なため削除しました。
また、GitLab Runnerのバージョンを更新しました。

2023-09-08 06:22 UTC, oguchi-shiori03 commented on doc/autoscaling.md
> +# サーバのポートを開放します
手順を「Autoscalingで作成されたインスタンス、CIサーバに適用されるセキュリティグループのインバウンドルールを追加する」という内容に変更しました。

2023-09-08 06:35 UTC, kumagoro1202 approved these changes

2023-09-08 06:35 UTC, merged