2023年度版の手順書修正
Fintan-contents/collaborage pull request #22
Opened 2023-09-12 00:59 UTC by oguchi-shiori03

2023-09-12 11:51 UTC, kumagoro1202 requested changes

2023-09-12 11:51 UTC, kumagoro1202 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
110行目にNablarchのExampleという記述が残っている。

2023-09-12 11:51 UTC, kumagoro1202 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
グランドデザインの図で「CentOS/dockerを前提に」となっていて古い。

2023-09-12 11:51 UTC, kumagoro1202 commented on doc/aws.md
> +- [マイグレーション](migration.md)
冒頭の説明で「Collaborage 1.0.0をお使いの方で、アプリケーションのビルドにJava11を使用したい方は、「マイグレーション」に進んでください。」とあるがリンク先の内容とあっていない。

2023-09-12 11:51 UTC, kumagoro1202 commented on doc/aws.md
> +- CQ/CIサーバのEC2はm6i.large、ルートボリューム20GB、データボリューム40GBでデフォルト提供します。
AWSのリソースの図で青枠とオレンジ枠の凡例がない。

2023-09-12 11:51 UTC, kumagoro1202 commented on doc/aws.md
> +- CQ/CIサーバのCloudWatchAgentで、メトリクス(ディスク使用率)をCloudWatchに送信します。
59行目のリンク先がモニタリングスクリプトなので
https://docs.aws.amazon.com/ja_jp/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html
こちらにするべきではないでしょうか。

2023-09-12 11:51 UTC, kumagoro1202 commented on doc/ami.md
> +  - nop/pass456-（Redmine、SonarQube、Rocket.Chat、GitBucket、GitLab、Subversion）
プロジェクト/リポジトリにnablarch-example-webとありますがnablarchに依存しないものにしたのではなかったでしたっけ？

2023-09-13 11:08 UTC, kumagoro1202 requested changes

2023-09-13 11:08 UTC, kumagoro1202 commented on doc/ami.md
> +        ```
ここで設定するのは712行目でつけた名前？

2023-09-13 11:08 UTC, kumagoro1202 commented on doc/dev.md
> +        https://download.oracle.com/java/17/archive/jdk-17.0.7_linux-x64_bin.tar.gz
Oracle Javaは使わないでください。

2023-09-13 11:08 UTC, kumagoro1202 commented on doc/dev.md
> +    - 名前: JDK17
ベースをJava17にするのであれば、この手順は不要or init.mdで設定するべきものでは。

2023-09-13 11:08 UTC, kumagoro1202 commented on doc/dev.md
> +    - 名前: JDK17
口頭で会話。ベースイメージをJava17で動いているJenkinsにするのでこの手順は不要。

追加で、マイグレーション手順のページにJava8、11を使う場合は～というセクション作ってここでやってるようなJDKの追加手順を記載するべき。

2023-09-13 11:08 UTC, kumagoro1202 commented on src/aws/script/config/params.config
> +AMAZON_LINUX_DEMO_PASS=
これユーザのパスワードに使われるんですよね？Amazon Linuxよりec2-userの方が適切な名前だと思いました。

2023-09-13 11:08 UTC, kumagoro1202 commented on src/aws/script/install-awscli.sh
> +sudo ./aws/install --update
Amazon Linuxって最初からAWS CLI V2入ってませんでしたっけ？

2023-09-13 11:08 UTC, kumagoro1202 commented on src/common/docker/ci-on-jenkins/dockerfiles/gitbucket/Dockerfile
> +RUN apt-get update -y && apt-get install -y netcat && apt-get clean
netcatって必須なんでしょうか？GitBucketのオフィシャルイメージ使うならDockerfile要らないんじゃないかと思いました。

2023-09-13 11:08 UTC, kumagoro1202 commented on src/common/pipeline/jenkins/java17/Jenkinsfile
> +        echo 'Create executable war'
executable warというところちょっと違和感ありました。executable jarとは言いますがexecutable warとは言わないかなと。warはexecutableなものじゃないですしCreate warじゃないですかね。

2023-09-13 11:08 UTC, kumagoro1202 commented on doc/migration.md
> +- 移行前のサーバと移行後のサーバは同一VPC上に存在していることを想定しています。
移行形態についてもう少し説明が必要だと思いました。完全移行はまったく同じ情報が参照できるようになるものですかね。Redmineの一部移行は何が移行できない(plugin？)のか、CI系が参照環境作成となっているのはどういう意味かというのを簡単に記載してほしいと思いました。

2023-09-13 11:08 UTC, kumagoro1202 commented on doc/migration.md
> +- [Redmineガイド - アップグレード](http://guide.redmine.jp/RedmineUpgrade/)
参考のリンクは何かあった時にこれ見てトラブルシュートしてねくらいの意味合いでしょうか？であれば末尾に持っていって手順についてさらに詳しく知りたい方はこちらをご覧ください。とか、参考リンクをつけている意図を記して欲しいです。説明なしにリンクが手順より前にあると、リンク先の内容の知識は前提だから読んでおいてと受け取られるかもと思いました。

2023-09-13 11:08 UTC, kumagoro1202 commented on doc/migration.md
> +- 移行前のサーバと移行後のサーバは同一VPC上に存在していることを想定しています。
あと各移行手順の冒頭にも何が移行できるか書いておいて欲しいです。

2023-09-13 11:08 UTC, kumagoro1202 commented on doc/migration.md
> +必要に応じて参照用の環境を作成します。
「必要に応じて」という部分をもう少し詳しく書いて欲しいです。古い環境と新環境でバージョンが違うとデータ移行してもエラーになって履歴が見れないこと、CIの履歴は最新が重要なこと、だから新環境ではパイプライン作成し直して新しく作ってること、だけど中には過去のビルド失敗原因のメッセージなどを参照したいことがあるかもしれないのでそういう時のためにこの手順を案内することなどを記載して欲しいです。

2023-09-14 01:35 UTC, oguchi-shiori03 commented on src/common/docker/ci-on-jenkins/dockerfiles/gitbucket/Dockerfile
> +RUN apt-get update -y && apt-get install -y netcat && apt-get clean
gitbucketの起動は
①docker compose up での起動
②起動確認（wait-for）
③サブディレクトリでの参照設定（gitbucket.sh）
の流れで行われているのですが、②の起動確認の処理でgitbucket-dbとの疎通の確認を行っているため、必要になります。

2023-09-15 03:32 UTC, oguchi-shiori03 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
画像の文言を修正しました。

2023-09-15 03:32 UTC, oguchi-shiori03 commented on doc/aws.md
> +- [マイグレーション](migration.md)
Java11マイグレーションのリンクをCollaborage 1.1.0版の「マイグレーション」（https://github.com/Fintan-contents/collaborage/blob/1.1.0/doc/aws.md#%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3）になるように変更しました。

2023-09-15 03:34 UTC, oguchi-shiori03 commented on doc/aws.md
> +- CQ/CIサーバのEC2はm6i.large、ルートボリューム20GB、データボリューム40GBでデフォルト提供します。
凡例が消えていたのでもとに戻しました。

2023-09-15 03:35 UTC, oguchi-shiori03 commented on doc/aws.md
> +- CQ/CIサーバのCloudWatchAgentで、メトリクス(ディスク使用率)をCloudWatchに送信します。
ご指摘の通りですのでリンクを修正しました。

2023-09-15 03:35 UTC, oguchi-shiori03 commented on doc/ami.md
> +  - nop/pass456-（Redmine、SonarQube、Rocket.Chat、GitBucket、GitLab、Subversion）
nablarchの記載が残っていたため削除しました。

2023-09-15 03:36 UTC, oguchi-shiori03 commented on doc/ami.md
> +        ```
ご指摘の通り作成したアラームの名称となります。
そのため、設定するのが作成したアラームの名称であること、記載しているのが設定例であることを追記しました。

2023-09-15 03:37 UTC, oguchi-shiori03 commented on doc/dev.md
> +        https://download.oracle.com/java/17/archive/jdk-17.0.7_linux-x64_bin.tar.gz
承知しました。
また、本項はJenkinsイメージをJDKベースに変更したことに伴い削除しています。

2023-09-15 03:37 UTC, oguchi-shiori03 commented on doc/dev.md
> +    - 名前: JDK17
JenkinsのDockerイメージをJDK17ベースに変更しました。
また、それに伴いdev.mdでの記載の削除＋migration.mdへの記載の追加を行いました。

2023-09-15 03:39 UTC, oguchi-shiori03 commented on src/aws/script/config/params.config
> +AMAZON_LINUX_DEMO_PASS=
名称を修正しました。
※名称として「ec2-user」を利用できなかったため、「EC2_USER」を使用しています。

2023-09-15 03:40 UTC, oguchi-shiori03 commented on src/aws/script/install-awscli.sh
> +sudo ./aws/install --update
インストール済ですが、コマンドの更新はしたほうがよい、ということで実施していました。
ですが、本スクリプトはAMIの初期セットアップのみで実行され、利用者による更新を想定していなかったため削除しました。

2023-09-15 03:40 UTC, oguchi-shiori03 commented on src/common/pipeline/jenkins/java17/Jenkinsfile
> +        echo 'Create executable war'
記載を修正しました。
また、口頭で指摘をいただいた通り、deploy/push-docker-imageのブランチごとにJenkinsファイルを分割しました（gitlabも対応済）。

2023-09-15 03:41 UTC, oguchi-shiori03 commented on doc/migration.md
> +- 移行前のサーバと移行後のサーバは同一VPC上に存在していることを想定しています。
移行形態の説明を追記しました。
移行手順の冒頭の説明を追記しています。

2023-09-15 03:41 UTC, oguchi-shiori03 commented on doc/migration.md
> +- [Redmineガイド - アップグレード](http://guide.redmine.jp/RedmineUpgrade/)
参考リンクの位置を変更しました。

2023-09-15 03:41 UTC, oguchi-shiori03 commented on doc/migration.md
> +必要に応じて参照用の環境を作成します。
記載を修正しました。

2023-09-15 05:08 UTC, oguchi-shiori03 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
Nablarch の記載が残っていたので削除しました。
また、プロジェクト内に同様の文言が残っていないかを確認し、削除しました。
※ServletContextListener.javaに関しては対応不要であることを口頭で確認済

2023-09-15 09:03 UTC, kumagoro1202 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
OSがAmazon Linuxになっちゃったのでその他のクラウドの話すると違和感がありますね。AL選んだ時点で可搬性はなくなってる。この図なくしましょうか。。

2023-09-15 09:10 UTC, kumagoro1202 commented on doc/aws.md
> +- [マイグレーション](migration.md)
そのリンクが冒頭にあるのは違和感あります。冒頭の説明はここに列挙してる目次へのリンクとするべきなので、Collaborage1.1.0から2.0.0環境に移行する場合はマイグレーションに進んでください。としてある方がしっくりきます。
Java11のマイグレーションガイドはマイグレーションのページの先頭に「1.0.0をご利用の方はこちらのマイグレーション手順もご参照ください。」とかで一応残しとくくらいでいいと思います。ここで大々的に扱うものではないかなと。

2023-09-15 09:18 UTC, kumagoro1202 commented on doc/ami.md
> +        ```
キャプチャがあるからスニペットで記載されたJSONは不要かなと思いました。

2023-09-15 09:30 UTC, kumagoro1202 commented on src/common/pipeline/jenkins/java17/Jenkinsfile
> +        echo 'Create executable war'
push-docker-imageの方のJenkinsfileにexecutable warの記述が残っています。

2023-09-15 11:27 UTC, oguchi-shiori03 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
画像を削除しました。

2023-09-15 11:29 UTC, oguchi-shiori03 commented on doc/aws.md
> +- [マイグレーション](migration.md)
マイグレーションへの誘導の文言を修正しました。
また、migration.mdの冒頭にJava11のマイグレーションガイドへのリンクを追加しました。

2023-09-15 11:31 UTC, oguchi-shiori03 commented on src/common/pipeline/jenkins/java17/Jenkinsfile
> +        echo 'Create executable war'
コメントを修正しました。

2023-09-19 00:21 UTC, oguchi-shiori03 commented on doc/ami.md
> +        ```
記載例を削除してキャプチャのみに変更しました。

2023-09-19 00:32 UTC, kumagoro1202 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
グランドデザインという見出しに違和感があります。基本方針とかポリシーとか何かいい感じの言葉ないですかね。

2023-09-19 06:37 UTC, kumagoro1202 requested changes

2023-09-19 06:37 UTC, kumagoro1202 commented on doc/ami.md
> +      - 開始時刻: 14:10 UCT (日本時間で23:10)
typo UTC

2023-09-19 06:40 UTC, kumagoro1202 commented on doc/migration.md
> +- [Redmineガイド - アップグレード](http://guide.redmine.jp/RedmineUpgrade/)
参考リンクはどういう場合に見てほしいものですか？それとも利用者に向けてではなく出典を明記したいからですか？参考リンクのあるなしがどういう基準なのか、利用者はどういう場合にリンク先を見るべきなのかがわかりません。全部のアプリに対して公式ドキュメントの移行手順が載っていてそれぞれ公式ドキュメントへのリンクを全部に書いているなら理解できるのですが、一部だけリンクを置いているのはどういう意図ですか？

2023-09-20 00:24 UTC, oguchi-shiori03 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
「基本方針」に文言を修正しました。

2023-09-20 00:26 UTC, oguchi-shiori03 commented on doc/migration.md
> +- [Redmineガイド - アップグレード](http://guide.redmine.jp/RedmineUpgrade/)
公式で手順が案内がされているものに関しては記載を行っていましたが、手順が存在しないアプリがあることから参考の記載は一律削除しました。

2023-09-20 00:26 UTC, oguchi-shiori03 commented on doc/ami.md
> +      - 開始時刻: 14:10 UCT (日本時間で23:10)
文言を修正しました。

2023-09-20 00:30 UTC, kumagoro1202 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
冒頭にある目次のリンクがグランドデザインのままになっています。

2023-09-20 00:35 UTC, oguchi-shiori03 commented on README.md
> +  - クラウドのテンプレート機能やdocker composeを使用する。
目次のリンクを修正しました。
そのほかに「グランドデザイン」の文言を利用している箇所がないことも確認済です。

2023-09-20 00:42 UTC, kumagoro1202 approved these changes

2023-09-20 00:42 UTC, merged