手順書修正
Fintan-contents/collaborage pull request #23
Opened 2023-09-25 02:53 UTC by oguchi-shiori03

2023-09-25 02:55 UTC, oguchi-shiori03 commented on doc/migration.md
> -- [Nexus](#nexus)
マイグレーションを行う場合、nexus→GitLabの順番で行わないと必要なDockerイメージが取得できないため順番を変更しています。

2023-09-25 09:14 UTC, kumagoro1202 requested changes

2023-09-25 09:14 UTC, kumagoro1202 commented on CHANGELOG.md
> +  ただし、いくつかのツールはこれまで利用できていた機能が使えなくなるため、最新の安定版にバージョンアップしていません。
Redmineだけですよね？カンバンプラグインが対応してないからと具体的に書きましょうか。

2023-09-25 09:14 UTC, kumagoro1202 commented on CHANGELOG.md
> +- 各アプリのバージョンアップとガイド更新を実施しました。
これは下の利用ツールのバージョンアップと重複して冗長なので無しでいいです。

2023-09-26 01:47 UTC, oguchi-shiori03 commented on CHANGELOG.md
> +  ただし、いくつかのツールはこれまで利用できていた機能が使えなくなるため、最新の安定版にバージョンアップしていません。
最新でないアプリはRedmineだけなので、記載をRedmineに限定し具体的な内容に変更しました。

2023-09-26 01:47 UTC, oguchi-shiori03 commented on CHANGELOG.md
> +- 各アプリのバージョンアップとガイド更新を実施しました。
冗長な記載を削除しました。

2023-09-26 02:00 UTC, kumagoro1202 commented on CHANGELOG.md
> +  ただし、いくつかのツールはこれまで利用できていた機能が使えなくなるため、最新の安定版にバージョンアップしていません。
> ただし、Redmineはプラグインの「Redmine Backlogs」が未対応のため、最新の安定版にバージョンアップしていません。

ただし、Redmineはプラグインの「Redmine Backlogs」が5.Xに未対応のため、4.2.10 (2023-03-05リリース)を採用しています。

とかの方がいいと思いました。

2023-09-26 02:11 UTC, oguchi-shiori03 commented on CHANGELOG.md
> +  ただし、いくつかのツールはこれまで利用できていた機能が使えなくなるため、最新の安定版にバージョンアップしていません。
記載例、ありがとうございます。
記載いただいた内容に文言を修正しました。

2023-09-26 04:38 UTC, kumagoro1202 approved these changes

2023-09-26 04:38 UTC, merged