GitLabで利用するDBのバージョンをダウングレード
Fintan-contents/collaborage pull request #29
Opened 2024-02-07 01:48 UTC by oguchi-shiori03

2024-02-08 08:47 UTC, kumagoro1202 requested changes

2024-02-08 08:47 UTC, kumagoro1202 commented on doc/migration.md
> +Collaborage 1.0.0をお使いの方は、こちらの[マイグレーション手順](https://github.com/Fintan-contents/collaborage/blob/1.1.0/doc/aws.md#%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3)もご参照ください。
直前の行のCollaborageバージョンは2.1.0では？

2024-02-08 08:47 UTC, kumagoro1202 commented on doc/migration.md
> +  ダウングレードの実施理由は[Changelog](../CHANGELOG.md)を参照してください。
CHANGELOGだけだとこの先リリースがあった時にどこを見ればいいのとなると思うので、2.1.0のセクションにリンクしておいてください。

2024-02-09 00:50 UTC, oguchi-shiori03 commented on doc/migration.md
> +Collaborage 1.0.0をお使いの方は、こちらの[マイグレーション手順](https://github.com/Fintan-contents/collaborage/blob/1.1.0/doc/aws.md#%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3)もご参照ください。
ご指摘の通りなので、バージョンを変更しました。

2024-02-09 01:19 UTC, oguchi-shiori03 commented on doc/migration.md
> +  ダウングレードの実施理由は[Changelog](../CHANGELOG.md)を参照してください。
2.1.0のセクションにリンクするように変更しました。

2024-02-09 04:18 UTC, kumagoro1202 approved these changes

2024-02-09 04:18 UTC, merged